variable "instance_type" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "ami" {}
variable "aws_key_name" {}
variable "aws_key_path" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "name_tag" {}
variable "owner_tag" {}
variable "uuid" {}
variable "jumpbox_user" {}
variable "jumpbox_type" {}
variable "cf_domain" {}
variable "cf_admin" {}
variable "cf_admin_password" {}
